# Generated by Django 3.0.3 on 2020-02-19 12:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('navn', models.CharField(max_length=50)),
                ('tidspunkt', models.DateTimeField(default=django.utils.timezone.now)),
                ('innhold', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bruker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('navn', models.CharField(max_length=50)),
                ('brukerNavn', models.CharField(max_length=50)),
                ('epost', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('bursdag', models.DateTimeField(blank=True, default=None)),
                ('alder', models.IntegerField()),
                ('strikkeNivaa', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rolle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolleNavn', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='deltokArrangement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrangementId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Arrangement')),
                ('brukerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Bruker')),
            ],
        ),
        migrations.AddField(
            model_name='bruker',
            name='rolleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Rolle'),
        ),
        migrations.AddField(
            model_name='arrangement',
            name='forfatterId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Bruker'),
        ),
    ]
