# Generated by Django 3.0.3 on 2020-02-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bruker',
            name='bursdag',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
