# Generated by Django 3.0.3 on 2020-03-11 10:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200304_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='innlegg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('dateTime', models.DateTimeField(default=datetime.datetime(2020, 3, 11, 11, 26, 56, 457107))),
                ('bruker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Innlegg',
                'verbose_name_plural': 'Innlegg',
            },
        ),
    ]
