# Generated by Django 3.0.3 on 2020-03-18 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200318_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='innlegg',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 17, 30, 37, 940741)),
        ),
    ]
