# Generated by Django 3.0.3 on 2020-02-19 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200219_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bruker',
            name='alder',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bruker',
            name='rolleId',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='website.Rolle'),
        ),
    ]
