# Generated by Django 3.0.3 on 2020-02-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200219_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bruker',
            name='strikkeNivaa',
            field=models.IntegerField(null=True),
        ),
    ]
