# Generated by Django 3.0.3 on 2020-02-21 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200219_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bruker',
            old_name='epost',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='bruker',
            old_name='brukerNavn',
            new_name='username',
        ),
    ]
