# Generated by Django 3.0.3 on 2020-02-21 23:33

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200222_0024'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bruker',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
