# Generated by Django 3.0.3 on 2020-02-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200222_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='bruker',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
    ]
