# Generated by Django 3.0.3 on 2020-02-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('website', '0008_bruker_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='bruker',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='bruker',
            name='is_superuser',
            field=models.BooleanField(default=True, verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='bruker',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
