# Generated by Django 3.0.3 on 2020-02-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200222_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bruker',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='superuser status'),
        ),
    ]
