# Generated by Django 3.0.3 on 2020-02-23 12:00

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200222_1638'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bruker',
            managers=[
                ('objects', website.models.rolleBrukerManager()),
            ],
        ),
        migrations.AddField(
            model_name='bruker',
            name='is_bedrift',
            field=models.BooleanField(default=False, verbose_name='superuser status'),
        ),
    ]
