# Generated by Django 3.0.3 on 2020-02-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200223_1300'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bruker',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='bruker',
            name='is_bedrift',
            field=models.BooleanField(default=False, verbose_name='bedrift status'),
        ),
    ]
