# Generated by Django 3.0.3 on 2020-02-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20200223_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bruker',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='bruker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='bruker',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='bruker',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='bruker',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='bruker',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='bruker',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='bruker',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
