# Generated by Django 3.0.3 on 2020-02-23 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20200223_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='bruker',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
