# Generated by Django 3.0.3 on 2020-02-23 16:23

from django.db import migrations
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20200223_1719'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bruker',
            managers=[
                ('objects', website.models.rolleBrukerManager()),
            ],
        ),
    ]
