# Generated by Django 3.0.3 on 2020-02-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20200223_1723'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bruker',
            managers=[
            ],
        ),
    ]
