# Generated by Django 3.0.3 on 2020-02-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20200223_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bruker',
            name='rolleId',
            field=models.IntegerField(),
        ),
    ]
