# Generated by Django 3.0.3 on 2020-02-25 20:49

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20200225_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bruker',
            name='navn',
        ),
        migrations.AlterField(
            model_name='bruker',
            name='username',
            field=models.CharField(error_messages={'unique': 'Brukeren med dette brukernavn finnes allerede.'}, help_text='Påkrevd. 150 tegn eller færre. Bare bokstaver, sifre og @ /. / + / - / _.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Brukernavn'),
        ),
    ]
