# Generated by Django 3.0.3 on 2020-02-26 09:39

from django.db import migrations
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20200225_2149'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='arrangement',
            managers=[
                ('objects', website.models.ArrangementManager()),
            ],
        ),
        migrations.RenameField(
            model_name='arrangement',
            old_name='forfatterId',
            new_name='forfatter',
        ),
    ]
