# Generated by Django 3.0.3 on 2020-02-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20200226_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrangement',
            options={'verbose_name': 'arrangement', 'verbose_name_plural': 'arrangementer'},
        ),
    ]
