# Generated by Django 3.0.3 on 2020-02-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20200226_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrangement',
            old_name='navn',
            new_name='type',
        ),
    ]
