# Generated by Django 3.0.3 on 2020-03-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20200229_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
